version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "80:80"
    tty:  true
    restart: unless-stopped
    container_name: nginx
    depends_on:
      - cryptopro

  cryptopro:
    build:
      context: .
      dockerfile: Dockerfile
    tty:  true
    restart: unless-stopped
    container_name: cryptopro